import type { DSStatus } from "@/components/ds"

type UserStatus = Extract<
  DSStatus,
  "active" | "pending" | "warning" | "inactive"
>

type UserRole =
  | "Quản trị hệ thống"
  | "Người phê duyệt"
  | "Người rà soát bảo mật"
  | "Chuyên viên phân tích"
  | "Kiểm toán viên"

type UserDepartment =
  | "Vận hành"
  | "Tài chính"
  | "Bảo mật"
  | "Mua sắm"
  | "Quản trị"

type DemoUser = {
  id: string
  name: string
  email: string
  role: UserRole
  department: UserDepartment
  status: UserStatus
  lastActive: string
  phone: string
  location: string
  manager: string
  notes: string
  permissions: string[]
  activity: {
    label: string
    timestamp: string
  }[]
}

const roleOptions: UserRole[] = [
  "Quản trị hệ thống",
  "Người phê duyệt",
  "Người rà soát bảo mật",
  "Chuyên viên phân tích",
  "Kiểm toán viên",
]

const departmentOptions: UserDepartment[] = [
  "Vận hành",
  "Tài chính",
  "Bảo mật",
  "Mua sắm",
  "Quản trị",
]

const statusOptions: { label: string; value: UserStatus }[] = [
  { label: "Đang hoạt động", value: "active" },
  { label: "Đang chờ", value: "pending" },
  { label: "Cảnh báo", value: "warning" },
  { label: "Không hoạt động", value: "inactive" },
]

const demoUsers: DemoUser[] = [
  {
    id: "USR-1001",
    name: "Mai Nguyen",
    email: "mai.nguyen@example.com",
    role: "Quản trị hệ thống",
    department: "Vận hành",
    status: "active",
    lastActive: "Hôm nay, 09:42",
    phone: "+84 24 5550 1001",
    location: "Hà Nội",
    manager: "Tran Minh",
    notes: "Phụ trách quản trị hệ thống cho các đội dịch vụ vận hành.",
    permissions: ["Quản lý người dùng", "Phê duyệt quy trình", "Xuất kiểm toán"],
    activity: [
      { label: "Đã phê duyệt yêu cầu truy cập REQ-2841", timestamp: "Hôm nay, 09:42" },
      { label: "Đã cập nhật nhóm rà soát Tài chính", timestamp: "Hôm qua, 16:08" },
      { label: "Đã xuất nhật ký kiểm toán", timestamp: "02/05, 10:30" },
    ],
  },
  {
    id: "USR-1002",
    name: "Daniel Park",
    email: "daniel.park@example.com",
    role: "Người phê duyệt",
    department: "Tài chính",
    status: "pending",
    lastActive: "Hôm qua, 17:18",
    phone: "+84 28 5550 1002",
    location: "TP. Hồ Chí Minh",
    manager: "Mai Nguyen",
    notes: "Đang chờ hoàn tất hướng dẫn phê duyệt tài chính.",
    permissions: ["Phê duyệt chi phí", "Rà soát báo cáo"],
    activity: [
      { label: "Đã mời vào không gian Tài chính", timestamp: "Hôm qua, 17:18" },
      { label: "Đã gán vai trò phê duyệt", timestamp: "Hôm qua, 17:10" },
    ],
  },
  {
    id: "USR-1003",
    name: "Linh Tran",
    email: "linh.tran@example.com",
    role: "Người rà soát bảo mật",
    department: "Bảo mật",
    status: "warning",
    lastActive: "03/05, 14:06",
    phone: "+84 24 5550 1003",
    location: "Đà Nẵng",
    manager: "Mai Nguyen",
    notes: "Quyền rà soát bảo mật cần tái xác nhận hằng quý.",
    permissions: ["Rà soát bảo mật", "Ngoại lệ chính sách", "Báo cáo truy cập"],
    activity: [
      { label: "Đã rà soát ngoại lệ EXC-1029", timestamp: "03/05, 14:06" },
      { label: "Đã gửi nhắc tái xác nhận", timestamp: "01/05, 08:00" },
    ],
  },
  {
    id: "USR-1004",
    name: "Sarah Kim",
    email: "sarah.kim@example.com",
    role: "Chuyên viên phân tích",
    department: "Mua sắm",
    status: "inactive",
    lastActive: "28/04, 11:25",
    phone: "+84 24 5550 1004",
    location: "Hà Nội",
    manager: "Minh Pham",
    notes: "Tạm không hoạt động trong khi quyền mua sắm đang được rà soát.",
    permissions: ["Báo cáo mua sắm"],
    activity: [
      { label: "Tài khoản đã bị vô hiệu hóa", timestamp: "29/04, 09:00" },
      { label: "Đã xem bảng điểm nhà cung cấp", timestamp: "28/04, 11:25" },
    ],
  },
  {
    id: "USR-1005",
    name: "Minh Pham",
    email: "minh.pham@example.com",
    role: "Kiểm toán viên",
    department: "Quản trị",
    status: "active",
    lastActive: "Hôm nay, 08:15",
    phone: "+84 28 5550 1005",
    location: "TP. Hồ Chí Minh",
    manager: "Tran Minh",
    notes: "Kiểm toán viên chính cho báo cáo quản trị và tuân thủ.",
    permissions: ["Rà soát kiểm toán", "Xuất bằng chứng", "Kiểm thử kiểm soát"],
    activity: [
      { label: "Đã rà soát kiểm soát CTL-442", timestamp: "Hôm nay, 08:15" },
      { label: "Đã tải gói bằng chứng", timestamp: "Hôm qua, 15:22" },
    ],
  },
  {
    id: "USR-1006",
    name: "An Vo",
    email: "an.vo@example.com",
    role: "Người phê duyệt",
    department: "Vận hành",
    status: "active",
    lastActive: "Hôm nay, 07:55",
    phone: "+84 24 5550 1006",
    location: "Hà Nội",
    manager: "Mai Nguyen",
    notes: "Xử lý hàng đợi phê duyệt dịch vụ cho khu vực miền Bắc.",
    permissions: ["Phê duyệt quy trình", "Rà soát yêu cầu dịch vụ"],
    activity: [
      { label: "Đã phê duyệt yêu cầu dịch vụ SR-1904", timestamp: "Hôm nay, 07:55" },
      { label: "Đã rà soát hàng đợi leo thang", timestamp: "Hôm qua, 13:44" },
    ],
  },
  {
    id: "USR-1007",
    name: "Hana Lee",
    email: "hana.lee@example.com",
    role: "Chuyên viên phân tích",
    department: "Tài chính",
    status: "pending",
    lastActive: "04/05, 16:20",
    phone: "+84 28 5550 1007",
    location: "TP. Hồ Chí Minh",
    manager: "Daniel Park",
    notes: "Đang chờ xác nhận không gian báo cáo tài chính.",
    permissions: ["Rà soát báo cáo"],
    activity: [
      { label: "Đã mời vào không gian báo cáo", timestamp: "04/05, 16:20" },
      { label: "Đã gán vai trò phân tích tài chính", timestamp: "04/05, 16:11" },
    ],
  },
  {
    id: "USR-1008",
    name: "Quang Le",
    email: "quang.le@example.com",
    role: "Người rà soát bảo mật",
    department: "Bảo mật",
    status: "active",
    lastActive: "04/05, 10:12",
    phone: "+84 24 5550 1008",
    location: "Đà Nẵng",
    manager: "Linh Tran",
    notes: "Rà soát quyền đặc quyền và ngoại lệ chính sách.",
    permissions: ["Rà soát bảo mật", "Báo cáo truy cập"],
    activity: [
      { label: "Đã đóng ngoại lệ truy cập EXC-1038", timestamp: "04/05, 10:12" },
      { label: "Đã rà soát danh sách tài khoản đặc quyền", timestamp: "03/05, 09:05" },
    ],
  },
  {
    id: "USR-1009",
    name: "Nina Patel",
    email: "nina.patel@example.com",
    role: "Kiểm toán viên",
    department: "Quản trị",
    status: "warning",
    lastActive: "02/05, 15:48",
    phone: "+84 28 5550 1009",
    location: "TP. Hồ Chí Minh",
    manager: "Minh Pham",
    notes: "Cần tái xác nhận quyền kiểm toán trước cuối tháng.",
    permissions: ["Rà soát kiểm toán", "Xuất bằng chứng"],
    activity: [
      { label: "Đã bắt đầu rà soát gói kiểm toán", timestamp: "02/05, 15:48" },
      { label: "Đã gửi nhắc tái xác nhận", timestamp: "01/05, 08:00" },
    ],
  },
  {
    id: "USR-1010",
    name: "Bao Hoang",
    email: "bao.hoang@example.com",
    role: "Chuyên viên phân tích",
    department: "Mua sắm",
    status: "active",
    lastActive: "02/05, 09:35",
    phone: "+84 24 5550 1010",
    location: "Hà Nội",
    manager: "Sarah Kim",
    notes: "Duy trì tiếp nhận nhà cung cấp và bảng điều khiển mua sắm.",
    permissions: ["Báo cáo mua sắm", "Rà soát nhà cung cấp"],
    activity: [
      { label: "Đã cập nhật bảng tiếp nhận nhà cung cấp", timestamp: "02/05, 09:35" },
      { label: "Đã rà soát hàng đợi onboarding nhà cung cấp", timestamp: "01/05, 14:28" },
    ],
  },
  {
    id: "USR-1011",
    name: "Iris Chen",
    email: "iris.chen@example.com",
    role: "Người phê duyệt",
    department: "Tài chính",
    status: "inactive",
    lastActive: "24/04, 12:18",
    phone: "+84 28 5550 1011",
    location: "TP. Hồ Chí Minh",
    manager: "Daniel Park",
    notes: "Tạm không hoạt động trong khi chờ chuyển phòng ban.",
    permissions: ["Phê duyệt chi phí"],
    activity: [
      { label: "Tài khoản đã bị vô hiệu hóa", timestamp: "25/04, 09:30" },
      { label: "Đã rà soát yêu cầu chi phí FIN-481", timestamp: "24/04, 12:18" },
    ],
  },
  {
    id: "USR-1012",
    name: "Tuan Dang",
    email: "tuan.dang@example.com",
    role: "Quản trị hệ thống",
    department: "Vận hành",
    status: "active",
    lastActive: "23/04, 18:02",
    phone: "+84 24 5550 1012",
    location: "Hà Nội",
    manager: "Mai Nguyen",
    notes: "Quản trị viên dự phòng cho tính liên tục của dịch vụ vận hành.",
    permissions: ["Quản lý người dùng", "Phê duyệt quy trình"],
    activity: [
      { label: "Đã cập nhật ánh xạ vai trò vận hành", timestamp: "23/04, 18:02" },
      { label: "Đã rà soát kết quả import người dùng", timestamp: "22/04, 11:16" },
    ],
  },
  {
    id: "USR-1013",
    name: "Ngoc Anh",
    email: "ngoc.anh@example.com",
    role: "Người phê duyệt",
    department: "Mua sắm",
    status: "active",
    lastActive: "22/04, 16:44",
    phone: "+84 24 5550 1013",
    location: "Hà Nội",
    manager: "Bao Hoang",
    notes: "Phê duyệt yêu cầu mua sắm và theo dõi tiến độ nhà cung cấp.",
    permissions: ["Phê duyệt quy trình", "Rà soát nhà cung cấp"],
    activity: [
      { label: "Đã phê duyệt yêu cầu mua sắm PR-2041", timestamp: "22/04, 16:44" },
      { label: "Đã rà soát hồ sơ nhà cung cấp mới", timestamp: "22/04, 09:18" },
    ],
  },
  {
    id: "USR-1014",
    name: "Hoai Nam",
    email: "hoai.nam@example.com",
    role: "Chuyên viên phân tích",
    department: "Tài chính",
    status: "pending",
    lastActive: "22/04, 13:09",
    phone: "+84 28 5550 1014",
    location: "TP. Hồ Chí Minh",
    manager: "Daniel Park",
    notes: "Đang chờ phân quyền bộ báo cáo ngân sách quý.",
    permissions: ["Rà soát báo cáo"],
    activity: [
      { label: "Đã gửi yêu cầu truy cập báo cáo ngân sách", timestamp: "22/04, 13:09" },
      { label: "Đã hoàn tất xác thực email", timestamp: "22/04, 12:52" },
    ],
  },
  {
    id: "USR-1015",
    name: "Thu Ha",
    email: "thu.ha@example.com",
    role: "Kiểm toán viên",
    department: "Quản trị",
    status: "active",
    lastActive: "21/04, 17:30",
    phone: "+84 24 5550 1015",
    location: "Hà Nội",
    manager: "Minh Pham",
    notes: "Theo dõi bằng chứng kiểm toán cho các quy trình quản trị.",
    permissions: ["Rà soát kiểm toán", "Xuất bằng chứng"],
    activity: [
      { label: "Đã tải gói bằng chứng AUD-118", timestamp: "21/04, 17:30" },
      { label: "Đã ghi chú kết quả kiểm thử kiểm soát", timestamp: "21/04, 10:14" },
    ],
  },
  {
    id: "USR-1016",
    name: "Duc Bui",
    email: "duc.bui@example.com",
    role: "Người rà soát bảo mật",
    department: "Bảo mật",
    status: "warning",
    lastActive: "21/04, 11:07",
    phone: "+84 24 5550 1016",
    location: "Đà Nẵng",
    manager: "Linh Tran",
    notes: "Cần cập nhật chứng nhận rà soát bảo mật trước kỳ đánh giá.",
    permissions: ["Rà soát bảo mật", "Ngoại lệ chính sách"],
    activity: [
      { label: "Đã mở ngoại lệ bảo mật EXC-1062", timestamp: "21/04, 11:07" },
      { label: "Đã nhận nhắc cập nhật chứng nhận", timestamp: "20/04, 15:26" },
    ],
  },
  {
    id: "USR-1017",
    name: "Lan Phuong",
    email: "lan.phuong@example.com",
    role: "Chuyên viên phân tích",
    department: "Vận hành",
    status: "active",
    lastActive: "20/04, 15:41",
    phone: "+84 28 5550 1017",
    location: "TP. Hồ Chí Minh",
    manager: "An Vo",
    notes: "Phân tích hàng đợi vận hành và báo cáo SLA hằng tuần.",
    permissions: ["Rà soát yêu cầu dịch vụ", "Báo cáo truy cập"],
    activity: [
      { label: "Đã cập nhật báo cáo SLA tuần", timestamp: "20/04, 15:41" },
      { label: "Đã phân loại hàng đợi dịch vụ", timestamp: "20/04, 09:36" },
    ],
  },
  {
    id: "USR-1018",
    name: "Khanh Vy",
    email: "khanh.vy@example.com",
    role: "Người phê duyệt",
    department: "Tài chính",
    status: "inactive",
    lastActive: "19/04, 08:55",
    phone: "+84 28 5550 1018",
    location: "TP. Hồ Chí Minh",
    manager: "Daniel Park",
    notes: "Tài khoản tạm dừng sau khi kết thúc vai trò phê duyệt tạm thời.",
    permissions: ["Phê duyệt chi phí"],
    activity: [
      { label: "Tài khoản đã bị vô hiệu hóa", timestamp: "19/04, 09:10" },
      { label: "Đã phê duyệt chi phí FIN-497", timestamp: "19/04, 08:55" },
    ],
  },
  {
    id: "USR-1019",
    name: "Thanh Son",
    email: "thanh.son@example.com",
    role: "Quản trị hệ thống",
    department: "Quản trị",
    status: "active",
    lastActive: "18/04, 18:20",
    phone: "+84 24 5550 1019",
    location: "Hà Nội",
    manager: "Tran Minh",
    notes: "Quản trị cấu hình hệ thống và điều phối phân quyền nâng cao.",
    permissions: ["Quản lý người dùng", "Xuất kiểm toán", "Kiểm thử kiểm soát"],
    activity: [
      { label: "Đã cập nhật cấu hình phân quyền", timestamp: "18/04, 18:20" },
      { label: "Đã rà soát nhật ký thay đổi hệ thống", timestamp: "18/04, 14:03" },
    ],
  },
  {
    id: "USR-1020",
    name: "My Linh",
    email: "my.linh@example.com",
    role: "Chuyên viên phân tích",
    department: "Mua sắm",
    status: "pending",
    lastActive: "18/04, 10:12",
    phone: "+84 24 5550 1020",
    location: "Hải Phòng",
    manager: "Bao Hoang",
    notes: "Đang chờ gán nhóm quyền phân tích chi phí nhà cung cấp.",
    permissions: ["Báo cáo mua sắm"],
    activity: [
      { label: "Đã gửi yêu cầu nhóm quyền mua sắm", timestamp: "18/04, 10:12" },
      { label: "Đã hoàn tất hồ sơ người dùng", timestamp: "18/04, 09:48" },
    ],
  },
  {
    id: "USR-1021",
    name: "Gia Huy",
    email: "gia.huy@example.com",
    role: "Người rà soát bảo mật",
    department: "Bảo mật",
    status: "active",
    lastActive: "17/04, 16:36",
    phone: "+84 24 5550 1021",
    location: "Đà Nẵng",
    manager: "Linh Tran",
    notes: "Rà soát quyền truy cập ứng dụng nội bộ và tài khoản đặc quyền.",
    permissions: ["Rà soát bảo mật", "Báo cáo truy cập"],
    activity: [
      { label: "Đã rà soát tài khoản đặc quyền", timestamp: "17/04, 16:36" },
      { label: "Đã đóng cảnh báo truy cập ACC-220", timestamp: "17/04, 11:19" },
    ],
  },
  {
    id: "USR-1022",
    name: "Bich Ngoc",
    email: "bich.ngoc@example.com",
    role: "Kiểm toán viên",
    department: "Tài chính",
    status: "warning",
    lastActive: "17/04, 09:24",
    phone: "+84 28 5550 1022",
    location: "TP. Hồ Chí Minh",
    manager: "Minh Pham",
    notes: "Cần bổ sung bằng chứng đối soát cho kỳ kiểm toán tài chính.",
    permissions: ["Rà soát kiểm toán", "Xuất bằng chứng"],
    activity: [
      { label: "Đã đánh dấu thiếu bằng chứng FIN-AUD-31", timestamp: "17/04, 09:24" },
      { label: "Đã gửi nhắc chủ sở hữu tài chính", timestamp: "16/04, 15:10" },
    ],
  },
  {
    id: "USR-1023",
    name: "Quynh Chi",
    email: "quynh.chi@example.com",
    role: "Người phê duyệt",
    department: "Vận hành",
    status: "active",
    lastActive: "16/04, 13:50",
    phone: "+84 24 5550 1023",
    location: "Hà Nội",
    manager: "An Vo",
    notes: "Phê duyệt luồng xử lý sự cố và yêu cầu thay đổi vận hành.",
    permissions: ["Phê duyệt quy trình", "Rà soát yêu cầu dịch vụ"],
    activity: [
      { label: "Đã phê duyệt thay đổi CHG-771", timestamp: "16/04, 13:50" },
      { label: "Đã rà soát sự cố INC-334", timestamp: "16/04, 09:33" },
    ],
  },
  {
    id: "USR-1024",
    name: "Van Long",
    email: "van.long@example.com",
    role: "Chuyên viên phân tích",
    department: "Quản trị",
    status: "inactive",
    lastActive: "15/04, 15:03",
    phone: "+84 28 5550 1024",
    location: "Cần Thơ",
    manager: "Minh Pham",
    notes: "Không hoạt động sau khi hoàn tất dự án báo cáo quản trị.",
    permissions: ["Rà soát báo cáo"],
    activity: [
      { label: "Tài khoản đã bị vô hiệu hóa", timestamp: "15/04, 16:00" },
      { label: "Đã xuất báo cáo quản trị", timestamp: "15/04, 15:03" },
    ],
  },
  {
    id: "USR-1025",
    name: "Minh Chau",
    email: "minh.chau@example.com",
    role: "Quản trị hệ thống",
    department: "Bảo mật",
    status: "active",
    lastActive: "15/04, 10:46",
    phone: "+84 24 5550 1025",
    location: "Đà Nẵng",
    manager: "Linh Tran",
    notes: "Quản trị chính sách truy cập và điều phối kiểm soát bảo mật.",
    permissions: ["Quản lý người dùng", "Rà soát bảo mật", "Ngoại lệ chính sách"],
    activity: [
      { label: "Đã cập nhật nhóm quyền bảo mật", timestamp: "15/04, 10:46" },
      { label: "Đã rà soát ngoại lệ chính sách", timestamp: "14/04, 17:25" },
    ],
  },
  {
    id: "USR-1026",
    name: "Hong Nhung",
    email: "hong.nhung@example.com",
    role: "Người phê duyệt",
    department: "Mua sắm",
    status: "pending",
    lastActive: "14/04, 14:12",
    phone: "+84 24 5550 1026",
    location: "Hà Nội",
    manager: "Ngoc Anh",
    notes: "Đang chờ xác nhận phạm vi phê duyệt mua sắm khu vực miền Bắc.",
    permissions: ["Rà soát nhà cung cấp"],
    activity: [
      { label: "Đã gán vai trò phê duyệt dự kiến", timestamp: "14/04, 14:12" },
      { label: "Đã gửi yêu cầu xác nhận phạm vi", timestamp: "14/04, 10:05" },
    ],
  },
  {
    id: "USR-1027",
    name: "Tien Dat",
    email: "tien.dat@example.com",
    role: "Kiểm toán viên",
    department: "Vận hành",
    status: "active",
    lastActive: "13/04, 17:42",
    phone: "+84 28 5550 1027",
    location: "TP. Hồ Chí Minh",
    manager: "Minh Pham",
    notes: "Kiểm toán quy trình vận hành và bằng chứng xử lý SLA.",
    permissions: ["Rà soát kiểm toán", "Kiểm thử kiểm soát"],
    activity: [
      { label: "Đã kiểm thử kiểm soát vận hành CTL-508", timestamp: "13/04, 17:42" },
      { label: "Đã xuất bằng chứng SLA", timestamp: "13/04, 11:20" },
    ],
  },
  {
    id: "USR-1028",
    name: "Phuong Thao",
    email: "phuong.thao@example.com",
    role: "Chuyên viên phân tích",
    department: "Tài chính",
    status: "warning",
    lastActive: "13/04, 09:18",
    phone: "+84 28 5550 1028",
    location: "TP. Hồ Chí Minh",
    manager: "Daniel Park",
    notes: "Cần hoàn tất rà soát quyền truy cập báo cáo tài chính.",
    permissions: ["Rà soát báo cáo"],
    activity: [
      { label: "Đã mở yêu cầu rà soát quyền báo cáo", timestamp: "13/04, 09:18" },
      { label: "Đã nhận nhắc từ hệ thống", timestamp: "12/04, 16:40" },
    ],
  },
  {
    id: "USR-1029",
    name: "Hoang Yen",
    email: "hoang.yen@example.com",
    role: "Người rà soát bảo mật",
    department: "Quản trị",
    status: "active",
    lastActive: "12/04, 15:37",
    phone: "+84 24 5550 1029",
    location: "Hà Nội",
    manager: "Thanh Son",
    notes: "Rà soát quyền quản trị hệ thống và lịch sử thay đổi cấu hình.",
    permissions: ["Rà soát bảo mật", "Xuất kiểm toán"],
    activity: [
      { label: "Đã rà soát lịch sử thay đổi cấu hình", timestamp: "12/04, 15:37" },
      { label: "Đã đóng cảnh báo quyền quản trị", timestamp: "12/04, 10:08" },
    ],
  },
  {
    id: "USR-1030",
    name: "Trung Kien",
    email: "trung.kien@example.com",
    role: "Chuyên viên phân tích",
    department: "Vận hành",
    status: "inactive",
    lastActive: "11/04, 18:04",
    phone: "+84 24 5550 1030",
    location: "Hải Phòng",
    manager: "An Vo",
    notes: "Không hoạt động sau khi chuyển khỏi nhóm phân tích vận hành.",
    permissions: ["Rà soát yêu cầu dịch vụ"],
    activity: [
      { label: "Tài khoản đã bị vô hiệu hóa", timestamp: "12/04, 08:30" },
      { label: "Đã bàn giao báo cáo vận hành", timestamp: "11/04, 18:04" },
    ],
  },
  {
    id: "USR-1031",
    name: "Nhat Minh",
    email: "nhat.minh@example.com",
    role: "Quản trị hệ thống",
    department: "Vận hành",
    status: "active",
    lastActive: "11/04, 14:16",
    phone: "+84 24 5550 1031",
    location: "Hà Nội",
    manager: "Mai Nguyen",
    notes: "Hỗ trợ quản trị người dùng và xử lý yêu cầu truy cập khẩn cấp.",
    permissions: ["Quản lý người dùng", "Phê duyệt quy trình"],
    activity: [
      { label: "Đã xử lý yêu cầu truy cập khẩn cấp", timestamp: "11/04, 14:16" },
      { label: "Đã rà soát danh sách tài khoản mới", timestamp: "11/04, 09:45" },
    ],
  },
  {
    id: "USR-1032",
    name: "Cam Tu",
    email: "cam.tu@example.com",
    role: "Người phê duyệt",
    department: "Tài chính",
    status: "pending",
    lastActive: "10/04, 16:33",
    phone: "+84 28 5550 1032",
    location: "TP. Hồ Chí Minh",
    manager: "Daniel Park",
    notes: "Đang chờ người quản lý xác nhận ngưỡng phê duyệt chi phí.",
    permissions: ["Phê duyệt chi phí"],
    activity: [
      { label: "Đã gửi yêu cầu xác nhận ngưỡng phê duyệt", timestamp: "10/04, 16:33" },
      { label: "Đã hoàn tất đào tạo quy trình tài chính", timestamp: "10/04, 11:12" },
    ],
  },
  {
    id: "USR-1033",
    name: "Bao Tran",
    email: "bao.tran@example.com",
    role: "Kiểm toán viên",
    department: "Bảo mật",
    status: "warning",
    lastActive: "10/04, 09:52",
    phone: "+84 24 5550 1033",
    location: "Đà Nẵng",
    manager: "Minh Pham",
    notes: "Cần xác nhận lại phạm vi kiểm toán bảo mật trước kỳ chốt.",
    permissions: ["Rà soát kiểm toán", "Rà soát bảo mật"],
    activity: [
      { label: "Đã mở nhắc xác nhận phạm vi kiểm toán", timestamp: "10/04, 09:52" },
      { label: "Đã tải bằng chứng bảo mật", timestamp: "09/04, 15:44" },
    ],
  },
  {
    id: "USR-1034",
    name: "Thuy Dung",
    email: "thuy.dung@example.com",
    role: "Chuyên viên phân tích",
    department: "Mua sắm",
    status: "active",
    lastActive: "09/04, 17:05",
    phone: "+84 24 5550 1034",
    location: "Hà Nội",
    manager: "Bao Hoang",
    notes: "Phân tích hiệu suất nhà cung cấp và tiến độ hợp đồng.",
    permissions: ["Báo cáo mua sắm", "Rà soát nhà cung cấp"],
    activity: [
      { label: "Đã cập nhật báo cáo hiệu suất nhà cung cấp", timestamp: "09/04, 17:05" },
      { label: "Đã rà soát danh sách hợp đồng quá hạn", timestamp: "09/04, 10:22" },
    ],
  },
  {
    id: "USR-1035",
    name: "Hai Dang",
    email: "hai.dang@example.com",
    role: "Người rà soát bảo mật",
    department: "Bảo mật",
    status: "active",
    lastActive: "09/04, 13:27",
    phone: "+84 24 5550 1035",
    location: "Đà Nẵng",
    manager: "Linh Tran",
    notes: "Theo dõi cảnh báo truy cập và điều phối rà soát ngoại lệ.",
    permissions: ["Rà soát bảo mật", "Ngoại lệ chính sách"],
    activity: [
      { label: "Đã đóng cảnh báo truy cập ACC-244", timestamp: "09/04, 13:27" },
      { label: "Đã phân công rà soát ngoại lệ", timestamp: "09/04, 08:50" },
    ],
  },
  {
    id: "USR-1036",
    name: "Kim Oanh",
    email: "kim.oanh@example.com",
    role: "Người phê duyệt",
    department: "Quản trị",
    status: "inactive",
    lastActive: "08/04, 10:39",
    phone: "+84 28 5550 1036",
    location: "Cần Thơ",
    manager: "Thanh Son",
    notes: "Không hoạt động sau khi quyền phê duyệt quản trị hết hạn.",
    permissions: ["Phê duyệt quy trình"],
    activity: [
      { label: "Tài khoản đã bị vô hiệu hóa", timestamp: "08/04, 11:00" },
      { label: "Đã phê duyệt quy trình ADM-222", timestamp: "08/04, 10:39" },
    ],
  },
  {
    id: "USR-1037",
    name: "Viet Anh",
    email: "viet.anh@example.com",
    role: "Chuyên viên phân tích",
    department: "Vận hành",
    status: "pending",
    lastActive: "07/04, 16:21",
    phone: "+84 24 5550 1037",
    location: "Hà Nội",
    manager: "An Vo",
    notes: "Đang chờ gán nhóm theo dõi yêu cầu dịch vụ miền Bắc.",
    permissions: ["Rà soát yêu cầu dịch vụ"],
    activity: [
      { label: "Đã gửi yêu cầu nhóm theo dõi dịch vụ", timestamp: "07/04, 16:21" },
      { label: "Đã hoàn tất hồ sơ gia nhập nhóm", timestamp: "07/04, 15:42" },
    ],
  },
  {
    id: "USR-1038",
    name: "Mai Khanh",
    email: "mai.khanh@example.com",
    role: "Kiểm toán viên",
    department: "Tài chính",
    status: "active",
    lastActive: "07/04, 11:14",
    phone: "+84 28 5550 1038",
    location: "TP. Hồ Chí Minh",
    manager: "Minh Pham",
    notes: "Kiểm toán viên hỗ trợ đối soát chi phí và kiểm soát tài chính.",
    permissions: ["Rà soát kiểm toán", "Xuất bằng chứng"],
    activity: [
      { label: "Đã đối soát bằng chứng chi phí", timestamp: "07/04, 11:14" },
      { label: "Đã tải báo cáo kiểm toán tài chính", timestamp: "06/04, 17:20" },
    ],
  },
  {
    id: "USR-1039",
    name: "Phuc Lam",
    email: "phuc.lam@example.com",
    role: "Quản trị hệ thống",
    department: "Mua sắm",
    status: "warning",
    lastActive: "06/04, 15:56",
    phone: "+84 24 5550 1039",
    location: "Hải Phòng",
    manager: "Mai Nguyen",
    notes: "Cần rà soát quyền quản trị tạm thời cho không gian mua sắm.",
    permissions: ["Quản lý người dùng", "Rà soát nhà cung cấp"],
    activity: [
      { label: "Đã nhận nhắc rà soát quyền tạm thời", timestamp: "06/04, 15:56" },
      { label: "Đã cập nhật phân quyền nhà cung cấp", timestamp: "06/04, 10:35" },
    ],
  },
  {
    id: "USR-1040",
    name: "Nguyen Khoa",
    email: "nguyen.khoa@example.com",
    role: "Người phê duyệt",
    department: "Bảo mật",
    status: "active",
    lastActive: "06/04, 09:08",
    phone: "+84 24 5550 1040",
    location: "Đà Nẵng",
    manager: "Linh Tran",
    notes: "Phê duyệt ngoại lệ bảo mật và yêu cầu truy cập đặc quyền.",
    permissions: ["Phê duyệt quy trình", "Ngoại lệ chính sách"],
    activity: [
      { label: "Đã phê duyệt ngoại lệ EXC-1080", timestamp: "06/04, 09:08" },
      { label: "Đã rà soát yêu cầu đặc quyền", timestamp: "05/04, 16:47" },
    ],
  },
  {
    id: "USR-1041",
    name: "Ha Giang",
    email: "ha.giang@example.com",
    role: "Chuyên viên phân tích",
    department: "Quản trị",
    status: "inactive",
    lastActive: "05/04, 14:32",
    phone: "+84 28 5550 1041",
    location: "Cần Thơ",
    manager: "Thanh Son",
    notes: "Tạm dừng sau khi hoàn tất phân tích dữ liệu quản trị.",
    permissions: ["Rà soát báo cáo"],
    activity: [
      { label: "Tài khoản đã bị vô hiệu hóa", timestamp: "05/04, 15:00" },
      { label: "Đã hoàn tất phân tích báo cáo quản trị", timestamp: "05/04, 14:32" },
    ],
  },
  {
    id: "USR-1042",
    name: "Diem My",
    email: "diem.my@example.com",
    role: "Người rà soát bảo mật",
    department: "Bảo mật",
    status: "pending",
    lastActive: "05/04, 08:49",
    phone: "+84 24 5550 1042",
    location: "Đà Nẵng",
    manager: "Linh Tran",
    notes: "Đang chờ hoàn tất gán phạm vi rà soát bảo mật ứng dụng.",
    permissions: ["Rà soát bảo mật"],
    activity: [
      { label: "Đã gửi yêu cầu gán phạm vi rà soát", timestamp: "05/04, 08:49" },
      { label: "Đã hoàn tất kiểm tra hồ sơ", timestamp: "04/04, 17:18" },
    ],
  },
]

function getDemoUser(id: string) {
  return demoUsers.find((user) => user.id === id)
}

export {
  departmentOptions,
  demoUsers,
  getDemoUser,
  roleOptions,
  statusOptions,
}
export type { DemoUser, UserDepartment, UserRole, UserStatus }
